### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by FEJackFly** [staeco/mauro#3]
![image](https://user-images.githubusercontent.com/24688308/91147824-625a2780-e6eb-11ea-859e-c8cd498db95d.png)

**Comment by yocontra** [comment]
If `cnpm` (what you're using to install) is a mirror of NPM then it probably hasn't picked up that package yet, or failed to pick it up. It works fine on regular NPM. Maybe because of the large size of the native package `cnpm` decided not to host it. I tried to search `cnpm` (https://npm.taobao.org/) but the website barely functions and the search doesn't return any results.

I'm sorry your government makes it so difficult to work with NPM but there isn't really anything I can do about it. You'll have to file an issue with `cnpm` and ask them why their mirror is broken, or use a VPN to bypass the firewall.
